# Copyright ©2018,2019 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
# http://www.gnu.org/software/gsrc
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME =    guile-sdl2
GARNAME = guile-sdl2
GARVERSION = 0.4.0
HOME_URL =  http://dthompson.us/projects/guile-sdl2.html
DESCRIPTION = guile scheme SDL2 (Simple DirectMedia Layer 2)  wrapper
define BLURB
Guile scheme SDL2 (Simple DirectMedia Layer 2)  wrapper. See also
"gnu/sdl"
endef

######################################################################
MASTER_SITES = https://files.dthompson.us/
MASTER_SUBDIR = $(GARNAME)/
DISTFILES = $(DISTNAME).tar.gz 
SIGFILES  = #$(DISTNAME).tar.gz.asc

BUILDDEPS =
LIBDEPS =

######################################################################

include ../../../gar/gar.lib/auto.mk
include ../../../gar/gar.lib/info.mk
include config.mk

