# Copyright © 2015,2017 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
# http://www.gnu.org/software/gsrc
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME = PDFKit
GARNAME = PDFKit
GARVERSION = 1.2.0
HOME_URL = http://www.non-gnu.org/gap/
DESCRIPTION =  GNUstep pdf libs framework, wrap xpdf
define BLURB
endef

######################################################################

MASTER_SITES = $(MASTER_SAVANNAH)
# or MASTER_SITES = $(MASTER_SAVANNAH_RELEASES)
MASTER_SUBDIR = gap/
DISTFILES = $(DISTNAME).tar.gz
SIGFILES =



BUILDDEPS =
LIBDEPS =

######################################################################

include ../../../gar/gar.lib/gnustep.mk
include config.mk
