## Configuration options ##

# to get around bug in 0.1.0 for now
CONFIGURE_OPTS ?= -DDEBUG_ASSERT_DISABLE  

BUILD_OPTS ?=  CPPFLAGS=-DDEBUG_ASSERT_DISABLE 
  CPPFLAGS+=-DDEBUG_ASSERT_DISABLE 
  CFLAGS+=-DDEBUG_ASSERT_DISABLE 
