# Copyright © 2020 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
# http://www.gnu.org/software/gsrc
#
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME = autogen-alpha
GARNAME = autogen-alpha
UPSTREAMNAME = autogen
GARVERSION = 5.19.96
HOME_URL = http://www.gnu.org/software/autogen/
DESCRIPTION =  autogen
define BLURB
endef


# later verson savannah git ?

######################################################################

MASTER_SITES = $(MASTER_GNU_ALPHA)
MASTER_SUBDIR = $(UPSTREAMNAME)/
DISTFILES = $(UPSTREAMNAME)-$(GARVERSION).tar.gz
SIGFILES =
#WORKSRC = $(WORKDIR)/$(GARNAME)-2-$(GARVERSION)/


BUILDDEPS =
LIBDEPS = 

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk
