# Copyright ©2018,2020,2021 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
# http://www.gnu.org/software/gsrc
#
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org


NAME =    xcb-proto
GARNAME = xcb-proto
GARVERSION =  1.14.1
HOME_URL = https://xcb.freedesktop.org
DESCRIPTION = xcb is an evolutionary descendent of xlib
# replaces xorg-xproto, etc.
define BLURB
endef

######################################################################
#https://xcb.freedesktop.org/dist/xcb-proto-1.13.tar.bz2

MASTER_SITES = ftp://ftp.freedesktop.org/
MASTER_SUBDIR = pub/individual/proto/
DISTFILES = $(DISTNAME).tar.xz
SIGFILES = $(DISTNAME).tar.xz.sig

BUILDDEPS = 
LIBDEPS = 

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

