# Copyright ©2017,2018 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org


NAME =   media-player-info 
GARNAME = media-player-info
GARVERSION = 24
HOME_URL = https://www.freedesktop.org/software/libevdev/doc/
DESCRIPTION = usb media player hardware info
define BLURB

endef

######################################################################
#https://freedesktop.org/software/media-player-info/media-player-info-23.tar.gz

MASTER_SITES = http://freedesktop.org/
MASTER_SUBDIR = software/$(GARNAME)/
DISTFILES = $(DISTNAME).tar.gz
SIGFILES  = 

BUILDDEPS = 
LIBDEPS = 

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

