*** Makefile.orig	2019-06-15 16:21:12.251490410 -0700
--- Makefile	2019-06-15 16:29:16.220924432 -0700
***************
*** 5,31 ****
  # Steve
  # --
  #
! #
  
  #
  #  PREFIX for installation.
  #
  PREFIX     = 
  
  
  #
  #  Installation Directories.
  #
! BINDIR      = /usr/bin
! TEMPDIR     = /usr/share/gnump3d
! CONFDIR     = /etc/gnump3d
! CACHEDIR    = /var/cache/gnump3d
! SERVEDIR    = /var/cache/gnump3d/serving
! MANDIR      = /usr/local/man/man1
! LOGDIR      = /var/log/gnump3d
! LIBDIR      = `perl bin/getlibdir`
! PLUGDIR     = $(LIBDIR)/gnump3d/plugins
! LANGDIR     = $(LIBDIR)/gnump3d/lang
  
  
  #
--- 5,31 ----
  # Steve
  # --
  #
! # hacked for GSRC
  
  #
  #  PREFIX for installation.
  #
  PREFIX     = 
  
  
  #
  #  Installation Directories.
  #
! BINDIR      = $(PREFIX)/bin
! TEMPDIR     = $(PREFIX)/share/gnump3d
! CONFDIR     = $(PREFIX)/etc/gnump3d
! CACHEDIR    = $(PREFIX)/var/cache/gnump3d
! SERVEDIR    = $(PREFIX)/var/cache/gnump3d/serving
! MANDIR      = $(PREFIX)/man/man1
! LOGDIR      = $(PREFIX)/var/log/gnump3d
! LIBDIR      = $(PREFIX)/lib/perl5
! PLUGDIR     = $(LIBDIR)/gnump3d/plugins
! LANGDIR     = $(LIBDIR)/gnump3d/lang
  
  
  #
***************
*** 114,157 ****
  
  
  install:
! 	install -d ${PREFIX}/${CONFDIR}
! 	install -d ${PREFIX}/${BINDIR}
! 	install -d ${PREFIX}/${TEMPDIR}
! 	install -d ${PREFIX}/${MANDIR}
! 	install -d ${PREFIX}/${PLUGDIR}
! 	install -d ${PREFIX}/${LANGDIR}
! 	install -d ${PREFIX}/${LOGDIR}
! 	install -d ${PREFIX}/${CACHEDIR}
! 	chmod 777 ${PREFIX}/${CACHEDIR}
! 	install -d ${PREFIX}/$(SERVEDIR)
! 	chmod 777 ${PREFIX}/${SERVEDIR}
! 	chmod a+rx ${PREFIX}/${LIBDIR}/gnump3d/
! 	chmod a+rx ${PREFIX}/${LIBDIR}/gnump3d/plugins
! 	chmod a+rx ${PREFIX}/${LIBDIR}/gnump3d/lang
! 	cp lib/gnump3d/*.pm ${PREFIX}/${LIBDIR}/gnump3d
! 	cp lib/gnump3d/plugins/*.pm ${PREFIX}/${PLUGDIR}
! 	-rm ${PREFIX}/${PLUGDIR}/bug.pm
! 	cp lib/gnump3d/lang/*.pm ${PREFIX}/${LANGDIR}
! 	cp bin/gnump3d2 ${PREFIX}/${BINDIR}
! 	chmod 755 ${PREFIX}/${BINDIR}/gnump3d2
! 	-ln -sf ${PREFIX}/${BINDIR}/gnump3d2 ${PREFIX}/${BINDIR}/gnump3d
! 	cp bin/gnump3d-top ${PREFIX}/$(BINDIR)
! 	chmod 755 ${PREFIX}/${BINDIR}/gnump3d-top
! 	cp bin/gnump3d-index ${PREFIX}/${BINDIR}
! 	chmod 755 ${PREFIX}/${BINDIR}/gnump3d-index
! 	cp man/gnump3d-top.1 ${PREFIX}/${MANDIR}
! 	cp man/gnump3d-index.1 ${PREFIX}/${MANDIR}
! 	cp man/gnump3d.1 ${PREFIX}/${MANDIR}
! 	cp man/gnump3d.conf.1 ${PREFIX}/${MANDIR}
! 	cp -R templates/* ${PREFIX}/${TEMPDIR}
! 	chmod -R a+r ${PREFIX}/${TEMPDIR}
! 	chmod +rx ${PREFIX}/${TEMPDIR}/*/
! 	if [ -e ${PREFIX}/${CONFDIR}/gnump3d.conf ]; then cp ${PREFIX}/${CONFDIR}/gnump3d.conf ${PREFIX}/${CONFDIR}/gnump3d.conf-orig ; fi
! 	sed "s#PLUGINDIR#${LIBDIR}#g" etc/gnump3d.conf > ${PREFIX}/${CONFDIR}/gnump3d.conf
! 	cp etc/mime.types ${PREFIX}/${CONFDIR}
! 	cp etc/file.types ${PREFIX}/${CONFDIR}
! 	-rm -f ${PREFIX}/$(LIBDIR)/gnump3d/FreezeThaw.pm
! 	-rm -f ${PREFIX}/$(LIBDIR)/gnump3d/playlist.pm
  
  
  profile:
--- 114,157 ----
  
  
  install:
! 	install -d ${CONFDIR}
! 	install -d ${BINDIR}
! 	install -d ${TEMPDIR}
! 	install -d ${MANDIR}
! 	install -d ${PLUGDIR}
! 	install -d ${LANGDIR}
! 	install -d ${LOGDIR}
! 	install -d ${CACHEDIR}
! 	chmod 777  ${CACHEDIR}
! 	install -d $(SERVEDIR)
! 	chmod 777  ${SERVEDIR}
! 	chmod a+rx ${LIBDIR}/gnump3d/
! 	chmod a+rx ${LIBDIR}/gnump3d/plugins
! 	chmod a+rx ${LIBDIR}/gnump3d/lang
! 	cp lib/gnump3d/*.pm ${LIBDIR}/gnump3d
! 	cp lib/gnump3d/plugins/*.pm ${PLUGDIR}
! 	-rm ${PLUGDIR}/bug.pm
! 	cp lib/gnump3d/lang/*.pm ${LANGDIR}
! 	cp bin/gnump3d2 ${BINDIR}
! 	chmod 755 ${BINDIR}/gnump3d2
! 	-ln -sf ${BINDIR}/gnump3d2 ${BINDIR}/gnump3d
! 	cp bin/gnump3d-top $(BINDIR)
! 	chmod 755 ${BINDIR}/gnump3d-top
! 	cp bin/gnump3d-index ${BINDIR}
! 	chmod 755 ${BINDIR}/gnump3d-index
! 	cp man/gnump3d-top.1 ${MANDIR}
! 	cp man/gnump3d-index.1 ${MANDIR}
! 	cp man/gnump3d.1 ${MANDIR}
! 	cp man/gnump3d.conf.1 ${MANDIR}
! 	cp -R templates/* ${TEMPDIR}
! 	chmod -R a+r ${TEMPDIR}
! 	chmod +rx ${TEMPDIR}/*/
! 	if [ -e ${CONFDIR}/gnump3d.conf ]; then cp ${CONFDIR}/gnump3d.conf ${CONFDIR}/gnump3d.conf-orig ; fi
! 	sed "s#PLUGINDIR#${LIBDIR}#g" etc/gnump3d.conf > ${CONFDIR}/gnump3d.conf
! 	cp etc/mime.types ${CONFDIR}
! 	cp etc/file.types ${CONFDIR}
! 	-rm -f $(LIBDIR)/gnump3d/FreezeThaw.pm
! 	-rm -f $(LIBDIR)/gnump3d/playlist.pm
  
  
  profile:
