# Copyright © 2016, 2017, 2018, 2019 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME =    libpng
GARNAME = libpng
GARVERSION = 1.6.37
HOME_URL = http://libpng.org/
DESCRIPTION =  libpng, official PNG reference library.
define BLURB
endef

######################################################################
# https://download.sourceforge.net/libpng/libpng-1.6.35.tar.xz

MASTER_SITES =  https://download.sourceforge.net/
MASTER_SUBDIR =  $(GARNAME)/
DISTFILES = $(DISTNAME).tar.xz  
SIGFILES =

BUILDDEPS =
LIBDEPS =

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

