# Copyright ©2018 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.

NAME =    HighlighterKit
GARNAME = HighlighterKit
GARVERSION = 0.1.3
HOME_URL = http://www.gnustep.org/
DESCRIPTION = highlights text, a library framework
define BLURB
endef


######################################################################

MASTER_SITES = $(MASTER_SAVANNAH_RELEASES)/
MASTER_SUBDIR = gnustep-nonfsf/
DISTFILES = $(DISTNAME).tar.gz
SIGFILES  = $(DISTNAME).tar.gz.sig

BUILDDEPS =
LIBDEPS =
CONFIGURE_SCRIPTS =
LICENSE = GNU Lesser General Public License v2.1

######################################################################

include ../../../gar/gar.lib/gnustep.mk
include config.mk


