# Copyright © 2016 Carl Hansen
#
# This file is part of GSRC.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org


NAME =    telepathy-logger
GARNAME = telepathy-logger
HOME_URL = http://www.gnome.org/
DESCRIPTION = telepathy-logger
define BLURB

endef
GARVERSION = 0.8.2
# module = telepathy-logger/telepathy-logger-0.8.2.tar.bz2

######################################################################

MASTER_SITES=http://telepathy.freedesktop.org/releases/
MASTER_SUBDIR = telepathy-logger/
DISTFILES = telepathy-logger-0.8.2.tar.bz2
SIGFILES = 

# hash = sha256:8fcad534d653b1b365132c5b158adae947810ffbae9843f72dd1797966415dae
BUILDDEPS = 
LIBDEPS = #  dbus dbus-glib glib gobject-introspection gtk-doc libxml2 sqlite3 telepathy-glib
SUGGESTS = 

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

