# Copyright ©2017, 2021Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
# http://www.gnu.org/software/gsrc
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org


NAME =    expat
GARNAME = expat
GARVERSION = 2.2.10
HOME_URL = https://libexpat.github.io/
DESCRIPTION = XML parser c library
define BLURB
endef

LICENSE = GNU LGPL

######################################################################
# https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2
MASTER_SITES = $(MASTER_GITHUB)/  
MASTER_SUBDIR = libexpat/libexpat/releases/download/R_2_2_10/ 
DISTFILES =  $(DISTNAME).tar.bz2
SIGFILES =     

BUILDDEPS = 
LIBDEPS = 

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

