# Copyright © 2016 Carl Hansen
#
# This file is part of GSRC.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org


NAME =    uncrustify
GARNAME = uncrustify
HOME_URL = http://www.gnome.org/
DESCRIPTION = uncrustify
define BLURB

endef
GARVERSION = 0.61
# module = project/uncrustify/uncrustify/uncrustify-0.61/uncrustify-0.61.tar.gz

######################################################################

MASTER_SITES=http://downloads.sourceforge.net/
MASTER_SUBDIR = project/uncrustify/uncrustify/uncrustify-0.61/
DISTFILES = uncrustify-0.61.tar.gz
SIGFILES = 

# hash = sha256:1df0e5a2716e256f0a4993db12f23d10195b3030326fdf2e07f8e6421e172df9
BUILDDEPS = 
LIBDEPS = #  c++
SUGGESTS = 

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

