
# Copyright © 2017 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME =    phantom_home
GARNAME = phantom_home
GARVERSION = 1.00
HOME_URL = http://www.gnome.org/
DESCRIPTION = Home automation software. Operate relays from parallel port.
define BLURB

endef

######################################################################
# https://ftp.gnu.org/gnu/phantom/home/phantom_home-1.00.tar.gz

MASTER_SITES = $(MASTER_GNU)/
MASTER_SUBDIR = gnu/phantom/home/
DISTFILES = $(DISTNAME).tar.gz 
SIGFILES =  

BUILDDEPS =
LIBDEPS =

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

