
# Copyright ©  2017 Carl Hansen carlhansen@gnu.org
#
# This file is part of GSRC, the GNU Source Release Collection.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME =    GtkGLExt
GARNAME = gtkglext
GARVERSION = 1.2.0
HOME_URL = http://projects.gnome.org/gtkglext/
DESCRIPTION =  OpenGL extension to gtk
define BLURB

endef
LICENSE = GNU LGPL 2.1

######################################################################
#http://downloads.sourceforge.net/gtkglext/gtkglext-1.2.0.tar.gz

MASTER_SITES =  http://downloads.sourceforge.net/
MASTER_SUBDIR = $(GARNAME)/
DISTFILES = $(DISTNAME).tar.gz 
SIGFILES =

# apt install libpangox-1.0-0 libpangox-1.0-dev  xorg-dev
BUILDDEPS =
LIBDEPS =

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

