
# Copyright © 2017 Carl Hansen <carlhansen@gnu.org>
#
# This file is part of GSRC, the GNU Source Release Collection.
#
# GSRC is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GSRC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GSRC.  If not, see <http://www.gnu.org/licenses/>.
#
# Send bug reports and comments about GSRC problems to bug-gsrc@gnu.org

NAME =    zlib
GARNAME = zlib
GARVERSION = 1.2.11
HOME_URL = http://www.zlib.net
DESCRIPTION = zlib compression library 
define BLURB

endef

######################################################################


MASTER_SITES = http://www.zlib.net/
MASTER_SUBDIR = 
DISTFILES = $(DISTNAME).tar.xz 
SIGFILES = $(DISTNAME).tar.xz.asc

BUILDDEPS =
LIBDEPS =

######################################################################

include ../../../gar/gar.lib/auto.mk
include config.mk

